version : '3.8'


services:
  red:
    build: .
    ports:
      - "5000:5000"

        #  green:
        # build: .
        # ports:
        # - "5001:5000"

  nginx:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - red
      - green
