version : '3.8'


services:
  red:
    build: .
    ports:
      - "5000:5000"
    networks:
      - loadbalancing

  green:
    build: .
    ports:
      - "5001:5000"
    networks:
      - loadbalancing

  nginx:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - red
      - green
    networks:
      - loadbalancing

networks:
  - loadbalancing
